import {getRandomInt} from './util.js';

const FilmCardMap = new Map([
  [`TITLE_COUNT`, 15],
  [`RATING_MIN`, 1],
  [`RATING_MAX`, 10],
  [`YEAR_MIN`, 1950],
  [`YEAR_MAX`, 2020],
  [`DURATION_MIN`, 60],
  [`DURATION_MAX`, 300],
  [`GENRE_COUNT`, 12],
  [`DESCRIPTION_COUNT`, 11],
  [`COMMENTS_MIN`, 0],
  [`COMMENTS_MAX`, 20],
]);


export const filmCard = {
  title: [
    `Avengers: Infinity War`,
    `Black Panther`,
    `Spider-Man: Homecoming`,
    `Captain America: Civil War`,
    `Venom`,
    `Aquaman`,
    `Spider-Man: Into the Spider-Verse`,
    `Wonder Woman`,
    `Logan`,
    `John Wick`,
    `Deadpool`,
    `The Hunger Games`,
    `The Hobbit: The Battle of the Five Armies`,
    `Batman v Superman: Dawn of Justice`,
    `Man of Steel`,
  ][Math.floor(Math.random() * FilmCardMap.get(`TITLE_COUNT`))],
  rating: getRandomInt(FilmCardMap.get(`RATING_MIN`), FilmCardMap.get(`RATING_MAX`)),
  year: getRandomInt(FilmCardMap.get(`YEAR_MIN`), FilmCardMap.get(`YEAR_MAX`)),
  duration: `${getRandomInt(FilmCardMap.get(`DURATION_MIN`), FilmCardMap.get(`DURATION_MAX`))}`,
  genre: [
    `Action`,
    `Adventure`,
    `Animation`,
    `Comedy`,
    `Crime`,
    `Drama`,
    `Fantasy`,
    `History`,
    `Horror`,
    `Music`,
    `Sci-Fi`,
    `Sport`,
    `Thriller`
  ][Math.floor(Math.random() * FilmCardMap.get(`GENRE_COUNT`))],
  poster: `images/posters/blackmail.jpg`,
  description: [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
    `Cras aliquet varius magna, non porta ligula feugiat eget.`,
    `Fusce tristique felis at fermentum pharetra.`,
    `Aliquam id orci ut lectus varius viverra.`,
    `Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante. `,
    `Phasellus eros mauris, condimentum sed nibh vitae, sodales efficitur ipsum.`,
    `Sed blandit, eros vel aliquam faucibus, purus ex euismod diam, eu luctus nunc ante ut dui.`,
    `Sed sed nisi sed augue convallis suscipit in sed felis.`,
    `Aliquam erat volutpat.`,
    `Nunc fermentum tortor ac porta dapibus.`,
    `In rutrum ac purus sit amet tempus.`,
  ][Math.floor(Math.random() * FilmCardMap.get(`DESCRIPTION_COUNT`))],
  commentsCount: `${getRandomInt(FilmCardMap.get(`COMMENTS_MIN`), FilmCardMap.get(`COMMENTS_MAX`))}`,
  isOnWatchlist: false,
  isWatched: true,
  isFavorite: false,
};
